// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awjnmvcalpirwfcfskus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3am5tdmNhbHBpcndmY2Zza3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mzk5NzgsImV4cCI6MjA3MDUxNTk3OH0.uM9_Ov5lX8E3YV5v7oHUKDDiAZEA-1-y7ycDVGSPNqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});