// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbrxtiueqrzwdmpxpcqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impicnh0aXVlcXJ6d2RtcHhwY3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzcwNTYsImV4cCI6MjA3MDUxMzA1Nn0.qK6hnOePnYTk1GgDctSolsZrPrMN6uaHdR9LsQJ6lkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});